title: Shashwat Garg
logo: /assets/img/me2.jpg
description: This is the website of Shashwat Garg. I write about AI, algorithms and psychology. 
email: garg.shashwat@gmail.com
url: https://gargshashwat.github.io
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
